### PR TITLE
[FIX] OCA/MQT#302: Use of astroid version 1.3.8

### PR DESCRIPTION
**Pull request by moylop260**
fix https://github.com/OCA/maintainer-quality-tools/issues/302

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can't we make that the set is compatible with latest version?

**Comment by moylop260** [comment]
@pedrobaeza 
We have freeze all requirements
I missed freeze astroid (my bad)

This issue need a fast-tracking because MQT don't show pylint error now:  OCA/maintainer-quality-tools#302

We could discuss a migration of libraries in other issue.

**Comment by pedrobaeza** [comment]
OK, fast-tracking this one to not break all the builds.

**Comment by moylop260** [comment]
@pedrobaeza 
Thank you
Now is MQT is health other time
green

**Comment by dreispt** [comment]
Thank you @moylop260

**Pull request merged**
