### PR TITLE
[ADD] invalid-commit: Add new check invalid-commit

### PR DESCRIPTION
**Pull request by moylop260**
- Verify the guideline [never-commit-the-transaction](https://github.com/oca/maintainer-tools/blob/master/CONTRIBUTING.md#never-commit-the-transaction)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lescobarvx** [comment]
:+1:

**Comment by guewen** [comment]
Commit could still be valid such as in cron tasks or for performance reasons.
This is also noticed by the guidelines in:

> All cr.commit() calls outside of the server framework from now on must have an explicit comment explaining why they are absolutely necessary, why they are indeed correct, and why they do not break the transactions. Otherwise they can and will be removed!

**Comment by moylop260** [comment]
@guewen 
You are right in some cases we need `cr.commit`
First step: Could you use cr.savepoint? No
Second step: Could you use a duplicated cursor to isolated the current operation (More info [here](https://www.odoo.com/es_ES/forum/ayuda-1/question/how-to-get-a-new-cursor-on-new-api-on-thread-63441))? No
Third step: Then use `cr.commit`, but add an explicit comment explaining... in this comment you can add `# pylint: disable=invalid-commit` to bypass this check.

**Comment by guewen** [comment]
> Third step: Then use cr.commit, but add an explicit comment explaining... in this comment you can add # pylint: disable=invalid-commit to bypass this check.

ok noted, thanks
:+1:

**Comment by oscarolar** [comment]
👍

**Comment by moylop260** [comment]
Somebody, could be merged it?

**Pull request merged**
