### PR TITLE
[ADD] dangerous-view-replace-wo-priority: Check dangerous view with replace but defined with low priority

### PR DESCRIPTION
**Pull request by moylop260**
More info in https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#inherited-xml

### CODE REVIEW

**Comment by dreispt** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by moylop260** [comment]
rebased thnks

**Comment by alan196** [comment]
:+1:

**Comment by oscarolar** [comment]
👍

**Pull request merged**
