### PR TITLE
Added ArchLinux package reference

### PR DESCRIPTION
**Pull request by hmrodrigues**
Adds reference to ArchLinux package in AUR (Arch User Repository)

### CODE REVIEW

**Comment by moylop260** [comment]
Thanks @hmrodrigues 

Registering this package in pypi we used a [OCA](https://odoo-community.org) official user/token.

What about use a OCA user to register it in https://aur.archlinux.org/packages/python-pylint-odoo ?

cc @max3903 @gurneyalex @pedrobaeza

**Comment by pedrobaeza** [comment]
OK, can be a good option. What do we need?

**Comment by hmrodrigues** [comment]
@pedrobaeza You need to create a account and then create a Orphan Request so the AUR guys transfer the package to the OCA account.

If you want, I can maintain the package after the transfer, you just need to add me as a co-maintainer.

**Comment by moylop260** [comment]
Closing since that there are not new comments since a while

**Pull request closed without merging**
