### PR TITLE
[REF] requirements: Update version of pylint and astroid

### PR DESCRIPTION
**Pull request by moylop260**
Update version of dependencies:
 - astroid==1.4.8
 - pylint==1.6.4
 - pylint-plugin-utils==0.2.4

For test use last sha:
 - https://github.com/PyCQA/astroid/commit/9979615
 - https://github.com/PyCQA/pylint/commit/05cc9a7

Useful in order to discuss new checks of pylint 1.6.4 from [MQT](https://github.com/oca/maintainer-quality-tools)

Fix https://github.com/OCA/pylint-odoo/pull/70

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why a freeze in an specific version?

**Comment by moylop260** [comment]
In order to avoid issues like as https://github.com/OCA/maintainer-quality-tools/issues/302#issuecomment-161017215

**Comment by pedrobaeza** [comment]
But that's something that is not going to happen anymore, and if so, then we act again, but this way we need to update each time there's a new version. API breakages are not common in the libraries.

**Comment by moylop260** [comment]
> that is not going to happen anymore

Yes, because we fixed freezing the libraries from https://github.com/OCA/pylint-odoo/pull/15
In fact, new version of pylint and astroid is not compatible with old version (before this PR) of pylint-odoo

This repository is critical because is used from all OCA's repositories.
A fail here represent a fail in all OCA's PR and requires a fast-tracking upgrade in order to fix incompatibility (But we don't have many people creating PRs)

IMHO is better a stable critical repository with updates each time there is a new version that a bugly critical repository with auto-updates.

What do you think?

**Comment by pedrobaeza** [comment]
OK, if the API compatibility is not assured, let's move this way.

**Comment by moylop260** [comment]
Thanks

**Comment by oscarolar** [comment]
:+1:

**Comment by moylop260** [comment]
ping

**Comment by agb80** [comment]
:+1: thansk for finish this @moylop260

**Pull request merged**
