### PR TITLE
[FIX] pylint_odoo: Fix running with jobs != 1

### PR DESCRIPTION
**Pull request by ondrej-kolman**
fix ruinning odoopylint with jobs != 1 
issue https://github.com/OCA/pylint-odoo/issues/491

### CODE REVIEW

**Comment by moylop260** [comment]
@ondrej-kolman 

Thank you for your fix

Could you fix the CI errors, please?

Also, could you add a unittest for jobs see the following example:
 - https://github.com/OCA/pylint-odoo/issues/491#issuecomment-2245779111

**Comment by moylop260** [comment]
@ondrej-kolman any update?

**Comment by ahaly-compass** [comment]
@ondrej-kolman any update?

**Comment by orgis** [comment]
Sorry guys, I'm busy, and I dont have time nor knowledge to fix CI errors. I will be happy if anybody could help.

**Pull request closed without merging**
