### PR TITLE
[ADD] pylint_odoo: Add main package.

### PR DESCRIPTION
**Pull request by moylop260**
# Pylint Odoo plugin

Enable custom checks for Odoo modules.

Code | Description | short name
--- | --- | ---
C7902 | Missing ./README.rst file. Template here: %s | missing-readme
C8101 | Missing author required "%s" in manifest file | manifest-required-author
C8102 | Missing required key "%s" in manifest file | manifest-required-key
C8103 | Deprecated key "%s" in manifest file | manifest-deprecated-key
C8104 | Use `CamelCase` "%s" in class name "%s". You can use oca-autopep8 of https://github.com/OCA/maintainer-tools to auto fix it. | class-camelcase
C8105 | License "%s" not allowed in manifest file. | license-allowed
C8201 | No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-` | no-utf8-coding-comment
E7901 | %s:%s %s | rst-syntax-error
E7902 | %s error: %s | xml-syntax-error
R8101 | Import `Warning` should be renamed as UserError `from openerp.exceptions import Warning as UserError` | openerp-exception-warning
W7901 | Dangerous filter without explicit `user_id` in xml_id %s | dangerous-filter-wo-user
W7902 | Duplicate xml record id %s | duplicate-xml-record-id
W7903 | %s | javascript-lint
W8101 | Detected api.one and api.multi decorators together. | api-one-multi-together
W8102 | Missing api.one or api.multi in copy function. | copy-wo-api-one
W8103 | Translation method _("string") in fields is not necessary. | translation-field
W8104 | api.one deprecated | api-one-deprecated
W8105 | attribute "%s" deprecated | attribute-deprecated
W8106 | Missing `super` call in "%s" method. | method-required-super
W8201 | Incoherent interpreter comment and executable permission. Interpreter: [%s] Exec perm: %s | incoherent-interpreter-exec-perm
W8202 | Use of vim comment | use-vim-comment

### CODE REVIEW

**Comment by nhomar** [comment]
:+1:

**Comment by oscarolar** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by dreispt** [comment]
Kudos for the great work!
:+1:

**Comment by GoodERPJeff** [comment]
Incoherent interpreter comment and executable permission

what this mean ?  all my python source file get this warning message

**Comment by moylop260** [comment]
We need a better message for this check.

That means,

You have a python file with execution permissions but you don't have a interpreter magic comment.
If you really needs a execution permission then add a magic comment (1)
If you don't needs a execution permission then remove it with: `chmod -x my_file.py`

(1) https://en.wikipedia.org/wiki/Shebang_%28Unix%29

**Comment by GoodERPJeff** [comment]
Thank you for your quickly response :+1: 

I am running pylint on MINGW on windows7

I added

> #!/usr/bin/env python

as the top line of all my .py files, that makes the warning removed, thank you

but my question is, python script is import by odoo framework, hardly run standalone, why we use this check? I checked many OCA addons file and seems no one can pass this check.

**Comment by dreispt** [comment]
It looks that this is a Windows specific issue: probably mingw is setting the +x attribute on all files.
Your best option is to use chmod -x on all addon files.

I'm curious: did you try to run pylint-odoo from the Windows cmd?

--dr 

No dia 29/12/2016, às 06:10, 开阖软件 Jeff Wang <notifications@github.com> escreveu:

**Comment by moylop260** [comment]
We don't have supported windows version yet.
Maybe we could use [appveyor CI](https://www.appveyor.com/) in order to test it.
What version of windows are you using?

**Pull request merged**
