### PR TITLE
[REF] README: Add new message manifest-author-string

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by moylop260** [comment]
Continuation of PR https://github.com/OCA/pylint-odoo/pull/4

**Comment by dreispt** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Please change log history too

**Comment by moylop260** [comment]
@pedrobaeza 
What is `Log history`?

**Comment by pedrobaeza** [comment]
I mean something like this: https://github.com/OCA/openupgradelib/blob/develop/HISTORY.rst

**Comment by moylop260** [comment]
Are you talking about https://github.com/OCA/pylint-odoo/releases?

**Comment by pedrobaeza** [comment]
Exactly. Document each version which changes contains

**Comment by moylop260** [comment]
You don't need a additional document.
We are use travis auto-deploy pypi and the correctly way for document each version is in github releases with tag signed.

**Comment by pedrobaeza** [comment]
But where is that history on pypi?

**Comment by moylop260** [comment]
You can enable ChangeLog in pbr but should be other pr

**Comment by moylop260** [comment]
@pedrobaeza 
FYI https://github.com/OCA/pylint-odoo/pull/6

**Comment by pedrobaeza** [comment]
For this :+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
