### PR TITLE
[REF] Migrate README.md to README.rst

### PR DESCRIPTION
**Pull request by moylop260**
pypi page use RST format, no support md format.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why is Travis red?

**Comment by moylop260** [comment]
Travis is green
travis_red

**Comment by max3903** [comment]
:+1:

**Comment by oscarolar** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by moylop260** [comment]
Thank you
Now is good!
beauty

**Pull request merged**
