### PR TITLE
[FIX] get_manifest_file: Get manifest file even if it is checking only one file and not the module like pre-commit uses

### PR DESCRIPTION
**Pull request by moylop260**
Closes https://github.com/OCA/pylint-odoo/issues/282

### CODE REVIEW

**Comment by moylop260** [comment]
Testing the same file of the issue:
 - image

Using master branch (before of this PR):
 - No show error
Using dev branch (this PR)
 - Show error.

**Comment by lmignon** [comment]
@moylop260 Do you plan to make a new release?

**Comment by moylop260** [comment]
@lmignon 

3.2.0 released

**Comment by lmignon** [comment]
@moylop260 Thank you!

**Pull request merged**
