### PR TITLE
[REF] development-status-allowed: Explicitly report possible values

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Review by moylop260 — APPROVED** [review]
👍 
Thank you!

I think next case should be get the value from pylint.conf file
Since that it is a default but not the final one if you are using a custom one

**Comment by dreispt** [comment]
@moylop260 Tests are failing, I'm not sure why. Can you assist please?

**Comment by moylop260** [comment]
@dreispt 

Done!

The issue was a comma `,`

And I use the dynamic values from configuration file in order to set the correct values if you have a custom configuration file

**Review by sbidoul — APPROVED** [review]

**Comment by moylop260** [comment]
@dreispt 

Could you check my last changes and give us your review, please?

In order to merge it

Regards!

**Pull request merged**
