### PR TITLE
[IMP] Add pylint check Redundant module name reference in xml_id

### PR DESCRIPTION
**Pull request by lescobarvx**
[IMP] Add pylint check Redundant module name reference in xml_id

### CODE REVIEW

**Comment by moylop260** [comment]
👍

**Comment by dreispt** [comment]
At least in 8.0, the `<report>` elements were required to use XML Ids with `module.name`.
Example: https://github.com/odoo/odoo/blob/9.0/addons/account_extra_reports/data/account_report.xml

**Comment by moylop260** [comment]
The `id="action_report_journal"`  is right a wrong redundant could be `id="account_extra_reports.action_report_journal"`
However, this check just is used in `<record id=...` case

**Comment by pedrobaeza** [comment]
@moylop260, please rebase. 

@dreispt, indeed, this only checks `<record>` tag, not other special tags like `<report>`, `<menuitem>`...

**Comment by moylop260** [comment]
I'm waiting the follow merge https://github.com/OCA/pylint-odoo/pull/26 to fix conflicts here

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
