### PR TITLE
Add __manifest__.py file for Odoo 10.0

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't this be better done in the script that automatically updates this folder?

**Comment by guewen** [comment]
I guess so, it wasn't obvious this file was auto-generated. Where can I find the script?

**Comment by moylop260** [comment]
I dont understood the comment Pedro
Could you help me to understand?

**Comment by moylop260** [comment]
:+1:
Thanks

**Comment by pedrobaeza** [comment]
Sorry for the confusion and the override of the PR. We have faced today the problem and solve it fast tracking another PR. I close this one.

**Pull request closed without merging**
