### PR TITLE
[IMP] don't report xml files referenced in report tag as unreferenced

### PR DESCRIPTION
**Pull request by hbrunn**
this supports xml files being pulled by some `<report ... xml="$file" xsl="$file" />` tag

### CODE REVIEW

**Comment by moylop260** [comment]
Good point!
Thanks!

Do you have planned add a test case for this matter?

**Comment by hbrunn** [comment]
no, but i should. setting to work in progress until i find time for that

**Comment by moylop260** [comment]
@JesusZapata 
Could you help us to add tests for this check?

**Comment by JesusZapata** [comment]
@hbrunn 
I go to made the test of this PR, could you give me an example when on the label `report` has `<report ... xml="$file" xsl="$file" />`
While more specific better

**Comment by hbrunn** [comment]
thank you so much for picking up my uncleaned garbage. Everything satisfying https://github.com/OCA/OCB/blob/10.0/odoo/import_xml.rng#L70 should be taken into account, but https://github.com/OCA/OCB/blob/8.0/addons/account/account_report.xml#L4 contains some specific examples

**Comment by JesusZapata** [comment]
@moylop260 
This PR now has test for this funcionality 
And travis is on green

**Pull request merged**
