### PR TITLE
[ADD] manifest-behind-migrations: check manifest version >= migrations 

### PR DESCRIPTION
**Pull request by antonag32**
A new check has been added to verify that the migrations and manifest
version for a module are up to date.

Closes https://github.com/OCA/pylint-odoo/issues/461.

### CODE REVIEW

**Comment by antonag32** [comment]
Draft as I need to functionally test this before merging.

**Comment by antonag32** [comment]
Tested yesterday on the big four and seems to work fine. Just as a note, pre-commit-vauxoo only checks migration scripts above 14.0 so this check will only apply to codebases on  Odoo 15 and up.

**Comment by moylop260** [comment]
@antonag32 

Could you fix the lints, please?

**Comment by antonag32** [comment]
> @antonag32
> 
> Could you fix the lints, please?

Done

**Comment by moylop260** [comment]
@luisg123v 

Please, review

**Comment by luisg123v** [comment]
@moylop260 could you set myself as a reviewer, please?

**Comment by moylop260** [comment]
@luisg123v 
github doesn't allow me to choose you as reviewer :(

**Pull request merged**
